### ISSUE TITLE
Add totals to main page and county pages?

### ISSUE THREAD

**Issue by jhannah** [opennebraska/tif#20]
@elviejito wrote:

> I also recommend adding totals to the main page - "Total for Nebraska:  " and to the County pages - "Total for _____ County:  "

Should the County and City lists be vertical tables like on the City page? Is that too much visual overload for the main page? Would they sort alphabetically instead of by TIF sum?

**Comment by elviejito** [comment]
The state page (or opening page) is very good as is.  I just noticed 
that you have little tool tips when one mouses over the columns in the 
graphic - I like that.  Maybe, rather than adding to the visual clutter, 
you could just add a tool tip to the Taxes Paid and Taxes Refunded 
graphics:

that for "Taxes Paid" pops up with "Total Taxes Paid for Nebraska: 
$XXXX" and for Taxes Refunded pops up with "Total Taxes Refunded for 
Nebraska:   $XXXX"

I like anything that encourages people to poke around on the website.

**Comment by jhannah** [comment]
@elviejito and I spoke on the phone a couple days ago. I think we settled on adding text "Taxes Refunded: TOTAL (red) Taxes Paid: TOTAL (green)" above the list of Counties and above the list of Cities. So this is a Perl + templates change, not a Google Charts change.

**Comment by elviejito** [comment]
One final change would be to have on the front page between the chart and "Click On Your County" a line that shows "Total Taxes Paid Statewide:  $xxxx"  and "Total Taxes Refunded Statewide:  $xxxx"   Seems to me we're looking at around $500,000,000 in Taxes Refunded.
